# Generated by Django 5.1.2 on 2024-11-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uf_alter_cidade_nome_alter_cidade_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do autor'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome da editora'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(max_length=100, verbose_name='Site da editora'),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email do leitor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_plub',
            field=models.DateField(verbose_name='Data de publicação do livro'),
        ),
    ]
