# Generated by Django 5.1.1 on 2024-11-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emprestimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_devolução',
            new_name='datadevolucao',
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_emprestimo',
            new_name='dataemprestimo',
        ),
        migrations.AddField(
            model_name='autor',
            name='cpf',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='autor',
            name='data_nasc',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='autor',
            name='telefone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='editora',
            name='cnpj',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='editora',
            name='data_fundacao',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='editora',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='editora',
            name='razao_social',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='editora',
            name='telefone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='autor',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='editora',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='editora',
            name='site',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leitor',
            name='cpf',
            field=models.CharField(max_length=100, unique=True, verbose_name='CPF do leitor'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('telefone', models.CharField(default='', max_length=255)),
                ('cpf', models.CharField(default='', max_length=255)),
                ('data_nasc', models.DateField(default='2000-01-01')),
                ('cidade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
